# Generated by Django 4.1.7 on 2024-07-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
